  name: sbd_back

  on:
    push:
      branches: [master]

  jobs:
    build:
      runs-on: ubuntu-22.04
      steps:
        - uses: appleboy/ssh-action@master
          with:
            port: ${{ secrets.port }}
            host: ${{ secrets.host }}
            username: ${{ secrets.username }}
            password: ${{ secrets.password }}
            script: |
            cd /d D:\SBD_Proj\SeoulEmsBack
            call sbdBackStart.bat