name: Remote Script Execution

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.host }}
          username: ${{ secrets.username }}
          port: ${{ secrets.port }}
          password: ${{ secrets.password }}
          script: |
            cd /home/mindone/
            ./emsBackAction.sh
