  name: sbd_back

  on:
    push:
      branches: [master]

  jobs:
    build:
      runs-on: ubuntu-22.04
      steps:
        - uses: appleboy/ssh-action@master
          with:
            port: ${{ secrets.port }}
            host: ${{ secrets.host }}
            username: ${{ secrets.user }}
            password: ${{ secrets.pw }}
            script:
              cd /d D:\SBD_Proj\SeoulEmsBack
              call sbdBackStart.bat